### ISSUE TITLE
Error in deploy.sh script

### ISSUE THREAD

**Issue by amon-ra** [glic3rinu/django-orchestra#10]
Installing using INSTALL.dev instructions I have several bugs in deploy.sh:
- Line 60: "$PYTHON_BIN $MANAGE migrate postupgradeorchestra --from $CURRENT_VERSION" throws an error. ( I think MANAGE variable must be defined before these line)
- LINE 102 : run "$PYTHON_BIN $MANAGE setupnginx" Throws the error:
```bash
Traceback (most recent call last):
  File "/home/orchestra/panel/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/home/orchestra/django-orchestra/orchestra/utils/sys.py", line 20, in wrapped
    return func(*args, **kwargs)
  File "/home/orchestra/django-orchestra/orchestra/management/commands/setupnginx.py", line 142, in handle
    raise CommandError("System user for running uwsgi must be provided.")
NameError: name 'CommandError' is not defined
```
I have modified the line as follows:
```bash
mkdir /etc/nginx/ssl
run "$PYTHON_BIN $MANAGE setupnginx --user=$USER"
```

**Comment by glic3rinu** [comment]
Just pushed the change to master, thanks!
